/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Model.Sistema;
import Model.Usuario;
import static Controllers.Multilista.lista;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author 201611277427
 */
public class Login extends javax.swing.JFrame {

    public static String nombreEmpleado;
    public static String nombreUsuario;
    public static int TipoUser;
    
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        TxtNombreUsuario.requestFocus();
        setIconImage(new ImageIcon(getClass().getResource("/Img_Ventanas/login.png")).getImage());
        lista.CargarPadres();
        lista.CargarUsuario();
        lista.CargarClientes();
        lista.CargarProductos();
        lista.CargarFactura();
        lista.CargarSistema();
        lista.CargarEmpresa();
        Usuario();
    }
    
    Usuario usuario = new Usuario();
      
    
    private void Usuario() {
        
        if (!usuario.HayUsuario()) {
            JOptionPane.showMessageDialog(rootPane, "No hay Usuarios Registrados");
            RegistrarUsuario registro = new RegistrarUsuario();
            registro.BtnRegistrar.setText("Nuevo Usuario");
            registro.Radmin.setSelected(true);
            registro.Radmin.setEnabled(false);
            registro.setAlwaysOnTop( true );
            registro.Rempleado.setEnabled(false);
            registro.BtnCancelar.setVisible(false);
            registro.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        LabelPass = new javax.swing.JLabel();
        TxtNombreUsuario = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        TxtPass = new javax.swing.JPasswordField();
        JlabelCerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Nombre de usuario");
        getContentPane().add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        LabelPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelPass.setForeground(new java.awt.Color(255, 255, 255));
        LabelPass.setText("Contraseña");
        getContentPane().add(LabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        TxtNombreUsuario.setBackground(new java.awt.Color(51, 102, 255));
        TxtNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        TxtNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TxtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 146, -1));

        BtnIngresar.setBackground(new java.awt.Color(255, 0, 0));
        BtnIngresar.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        BtnIngresar.setContentAreaFilled(false);
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, 30));

        TxtPass.setBackground(new java.awt.Color(51, 102, 255));
        TxtPass.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        TxtPass.setForeground(new java.awt.Color(255, 255, 255));
        TxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPassKeyTyped(evt);
            }
        });
        getContentPane().add(TxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 146, -1));

        JlabelCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JlabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        JlabelCerrar.setText("X");
        JlabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JlabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlabelCerrarMouseExited(evt);
            }
        });
        getContentPane().add(JlabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 20, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventanas/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        String user = TxtNombreUsuario.getText();
        String pass = String.valueOf(TxtPass.getPassword());
        
        if (!user.equals("") && !pass.equals("")) {
            if (usuario.HayUsuario()) {
                if (usuario.Validar(user,pass)) {  
                    VentanaPrincipal main = new VentanaPrincipal();
                    
                    nombreEmpleado = usuario.NombreEmpleado(user);
                    nombreUsuario = user;
                    TipoUser = usuario.TipoUsuario(user);
                    main.Lusuario.setText(user.toUpperCase());
                    
                    if (TipoUser == 1) {
                        main.MenuConfig.setVisible(true);
                        main.ItemInventario.setVisible(true);
                        main.ItemExportar.setVisible(true);
                        main.ItemVerRegistros.setVisible(true);
                    }else{
                        main.MenuConfig.setVisible(false);
                        main.ItemInventario.setVisible(false);
                        main.ItemExportar.setVisible(false);
                        main.ItemVerRegistros.setVisible(false);
                    }
                    main.setVisible(true);
                    Sistema sistema = new Sistema();
                    sistema.InsertarHistorial("Ha Iniciado Sesion");
                    sistema.ObtenerDias();
                    this.dispose();

                }else{
                    //Usuario / contraseña incorrecta
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrecta !");
                    TxtNombreUsuario.requestFocus();
                    TxtPass.setText("");
                    TxtNombreUsuario.setText("");
                }
            }else{
                Usuario();
            }
        }else{
            //Los campos esta vacios
            JOptionPane.showMessageDialog(null, "Campos Vacios !");
            TxtNombreUsuario.requestFocus();
        }
        
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void JlabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JlabelCerrarMouseClicked

    private void JlabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelCerrarMouseEntered
        JlabelCerrar.setForeground(Color.GRAY);
        
    }//GEN-LAST:event_JlabelCerrarMouseEntered

    private void JlabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelCerrarMouseExited
        JlabelCerrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_JlabelCerrarMouseExited

    private void TxtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreUsuarioKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z')) evt.consume();
    }//GEN-LAST:event_TxtNombreUsuarioKeyTyped

    private void TxtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPassKeyTyped
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            BtnIngresar.doClick();
        }
    }//GEN-LAST:event_TxtPassKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel JlabelCerrar;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JTextField TxtNombreUsuario;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
