/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cliente;
import Model.Sistema;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author 201611277427
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    private long Id;
    
    public RegistrarCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("REGISTRAR CLIENTE");
        setIconImage(new ImageIcon(getClass().getResource("/Img_Ventanas/user-1.png")).getImage());
        Cerrar();
        Botones();
    }
    public void Datos(String nombre, String apellido, long identificacion, String correo, Long telefono) {
        TxtNombre.setText(nombre);
        TxtApellido.setText(apellido);
        this.Id = identificacion;
        TxtId.setText(String.valueOf(identificacion));
        TxtId.setEnabled(false);
        TxtCorreo.setText(correo);
        TxtCorreo2.setText(correo);
        TxtTelefono.setText(String.valueOf(telefono));
    }
    private void Botones(){
        String texto = BtnRegistrar.getText();
        if (texto.equals("Actualizar")) {
            BtnRegistrar.setEnabled(true);
        }
    }
    
    private void Cerrar(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e){
                    comfirmar();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
        }
    }
    public void comfirmar(){
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRegistrar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtCorreo = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtId = new javax.swing.JTextField();
        TxtCorreo2 = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/aceptar.png"))); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setMargin(new java.awt.Insets(2, 3, 2, 3));
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setMargin(new java.awt.Insets(2, 3, 2, 3));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 32, -1, -1));

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 70, -1, -1));

        jLabel3.setText("Identificacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 111, -1, -1));

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 149, -1, -1));

        jLabel5.setText("Confirmar Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 187, -1, -1));

        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 227, 83, -1));

        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 29, 138, -1));

        TxtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 146, 172, -1));

        TxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 67, 138, -1));

        TxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdKeyTyped(evt);
            }
        });
        getContentPane().add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 108, 138, -1));

        TxtCorreo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCorreo2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreo2KeyTyped(evt);
            }
        });
        getContentPane().add(TxtCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 184, 172, -1));

        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 224, 96, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        String nombre = TxtNombre.getText();
        String apellido = TxtApellido.getText();
        String correo1 = TxtCorreo.getText();
        String correo2 = TxtCorreo2.getText();
                
        if (nombre.equals("") && apellido.equals("") && correo1.equals("") && correo2.equals("") && TxtId.getText().equals("") && TxtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Todos los campos son Obligatorios");
        }else if (correo1.length() > 10 && correo2.length() > 10) {
                long id = 0;
                long telefono = 0;
                try {
                    telefono = Long.parseLong(TxtTelefono.getText());
                    id = Long.parseLong(TxtId.getText());
                } catch (Exception e) {
                    System.out.println("Error "+e);
                }
                
                if (BtnRegistrar.getText().equals("Registrar")) {
                    Cliente cliente = new Cliente(nombre,apellido,id,correo1,telefono);
                    cliente.Insertar();
                    Modal modal = new Modal(new javax.swing.JFrame(), true);
                    modal.TxtMensaje.setText("Cliente Registrado");
                    modal.setVisible(true);
                    Sistema sistema = new Sistema();
                    sistema.InsertarHistorial("Ha Registrado un Cliente");
                }else{
                    Cliente cliente = new Cliente(nombre,apellido,id,correo1,telefono);
                    cliente.Actualizar(Id);
                    Modal modal = new Modal(new javax.swing.JFrame(), true);
                    modal.TxtMensaje.setText("Datos Actualizados");
                    modal.setVisible(true);
                    Sistema sistema = new Sistema();
                    sistema.InsertarHistorial("Ha Actualizado un Cliente");
                }
                ListaCliente.BtnActualizar.doClick();
                this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un Correo Valido");
        }
        
        
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TxtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < '.' || c > '@')) evt.consume();
    }//GEN-LAST:event_TxtCorreoKeyTyped

    private void TxtCorreo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreo2KeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < '.' || c > '@')) evt.consume();
    }//GEN-LAST:event_TxtCorreo2KeyTyped

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c != KeyEvent.VK_SPACE) ) evt.consume();
    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c != KeyEvent.VK_SPACE) ) evt.consume();
    }//GEN-LAST:event_TxtApellidoKeyTyped

    private void TxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        }
    }//GEN-LAST:event_TxtIdKeyTyped

    private void TxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if(Character.isLetter(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        }
    }//GEN-LAST:event_TxtTelefonoKeyTyped

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void TxtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoKeyReleased
        String correo = TxtCorreo.getText();
        String email = "";
        
        for (int x = 0; x < correo.length(); x++) {
            if (correo.charAt(x) == '@') {
                for (int i = x; i < correo.length(); i++) {
                    email = email + correo.charAt(i);
                }
                break;
            }
        }
        if (correo.length() > 10) {
            if (email.equals("@gmail.com") || email.equals("@hotmail.com")
                    || email.equals("@yahoo.com") || email.equals("@hotmail.es") 
                    || email.equals("@outlook.com")) {
                TxtCorreo.setBackground(Color.decode("#BCEE68"));
                TxtCorreo2.requestFocus();
            }else{
               TxtCorreo.setBackground(Color.decode("#F9A28F"));
            }
        }else{
            TxtCorreo.setBackground(Color.decode("#F9A28F"));
        }
    }//GEN-LAST:event_TxtCorreoKeyReleased

    private void TxtCorreo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreo2KeyReleased
        String correo2 = TxtCorreo2.getText();
        String correo1 = TxtCorreo.getText();
        String email = "";
        
        for (int x = 0; x < correo2.length(); x++) {
            if (correo2.charAt(x) == '@') {
                for (int i = x; i < correo2.length(); i++) {
                    email = email + correo2.charAt(i);
                }
                break;
            }
        }
        if (correo2.length() > 10) {
            if (email.equals("@gmail.com") || email.equals("@hotmail.com")
                    || email.equals("@yahoo.com") || email.equals("@hotmail.es") 
                    || email.equals("@outlook.com")) {
                if (correo1.equals(correo2)) {
                    TxtCorreo2.setBackground(Color.decode("#BCEE68"));
                    BtnRegistrar.setEnabled(true);
                }else{
                    BtnRegistrar.setEnabled(false);
                    TxtCorreo2.setBackground(Color.decode("#F9A28F"));
                }
            }else{
               TxtCorreo2.setBackground(Color.decode("#F9A28F"));
            }
        }else{
            TxtCorreo2.setBackground(Color.decode("#F9A28F"));
        }
    }//GEN-LAST:event_TxtCorreo2KeyReleased

    private void TxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyReleased
        String nombre = TxtNombre.getText();
        if (!nombre.equals("")) {
            char[] caracteres = nombre.toCharArray();
            caracteres[0] = Character.toUpperCase(caracteres[0]);
            // el -2 es para evitar una excepción al caernos del arreglo
            for (int i = 0; i < nombre.length() - 2; i++) // Es 'palabra'
            {
                if (caracteres[i] == ' ' || caracteres[i] == '.' || caracteres[i] == ',') {
                    // Reemplazamos
                    caracteres[i + 1] = Character.toUpperCase(caracteres[i + 1]);
                }
            }
            String nuevo =  new String(caracteres);
            TxtNombre.setText(nuevo);
        }
    }//GEN-LAST:event_TxtNombreKeyReleased

    private void TxtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoKeyReleased
        String apellido = TxtApellido.getText();
        if (!apellido.equals("")) {
            char[] caracteres = apellido.toCharArray();
            caracteres[0] = Character.toUpperCase(caracteres[0]);
            // el -2 es para evitar una excepción al caernos del arreglo
            for (int i = 0; i < apellido.length() - 2; i++) // Es 'palabra'
            {
                if (caracteres[i] == ' ' || caracteres[i] == '.' || caracteres[i] == ',') {
                    // Reemplazamos
                    caracteres[i + 1] = Character.toUpperCase(caracteres[i + 1]);
                }
            }
            String nuevo =  new String(caracteres);
            TxtApellido.setText(nuevo);
        }
    }//GEN-LAST:event_TxtApellidoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    public static javax.swing.JButton BtnRegistrar;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtCorreo2;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
