/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Producto;
import Model.Sistema;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author 201611277427
 */
public class RegistrarProducto extends javax.swing.JFrame {

    /**
     * Creates new form GuardarProducto
     */
    private int codi;
    private String texto1;

    public RegistrarProducto() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("REGISTRAR PRODUCTO");
        Cerrar();
    }

    DecimalFormat formato = new DecimalFormat("###,###.##");

    public void Datos(int codigo, String nombre, int cant, float precio, int estado) {
        TxtCodigo.setText(String.valueOf(codigo));
        TxtNombre.setText(nombre);
        SpinCantidad.setValue(cant);
        TxtPrecio.setText(String.valueOf(formato.format(precio)));
        TxtCodigo.setEditable(false);
        this.codi = codigo;
        if (estado == 1) {
            RActivo.setSelected(true);
            RActivo.setEnabled(true);
            RActivo.setText("Activo");
        } else {
            RActivo.setText("Inactivo");
        }
    }

    private void Cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    comfirmar();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
        }
    }

    public void comfirmar() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SpinCantidad = new javax.swing.JSpinner();
        TxtCodigo = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        RActivo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo ");

        jLabel2.setText("Nombre ");

        jLabel3.setText("Cantidad ");

        jLabel4.setText("Precio ");

        BtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/aceptar.png"))); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.setMargin(new java.awt.Insets(2, 2, 2, 4));
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SpinCantidad.setModel(new javax.swing.SpinnerNumberModel(15, 1, 100, 1));

        TxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyTyped(evt);
            }
        });

        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });

        TxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyTyped(evt);
            }
        });

        RActivo.setText("Activo");
        RActivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RActivoMousePressed(evt);
            }
        });

        jLabel5.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RActivo)
                            .addComponent(SpinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SpinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RActivo)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BtnAgregar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if (!TxtNombre.getText().equals("") && !TxtCodigo.getText().equals("") && !TxtPrecio.getText().equals("")) {
            if (TxtCodigo.getText().length() == 5) {
                int estado = 0;
                if (RActivo.isSelected()) {
                    estado = 1;
                } else {
                    estado = 0;
                }
                int codigo = Integer.parseInt(TxtCodigo.getText());
                String nombre = TxtNombre.getText();
                int cant = (int) SpinCantidad.getValue();
                float precio = Float.parseFloat(TxtPrecio.getText().replace(".", ""));

                if (BtnAgregar.getText().equals("Agregar")) {
                    Producto producto = new Producto(codigo, nombre, cant, precio, estado);
                    producto.Insertar();
                    Modal modal = new Modal(new javax.swing.JFrame(), true);
                    modal.TxtMensaje.setText("Producto Registrado");
                    modal.setVisible(true);
                    Sistema sistema = new Sistema();
                    sistema.InsertarHistorial("Ha Registrado un Producto");
                } else {
                    Producto producto = new Producto(codigo, nombre, cant, precio, estado);
                    producto.Actualizar(codi);
                    Modal modal = new Modal(new javax.swing.JFrame(), true);
                    modal.TxtMensaje.setText("Producto Actualizado");
                    modal.setVisible(true);
                    Sistema sistema = new Sistema();
                    sistema.InsertarHistorial("Ha Actualizado un Producto");
                }
                ListaInventario.BtnActualizar.doClick();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un codigo de 5 digitos");
                TxtCodigo.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son Obligatorios");
            TxtCodigo.requestFocus();
        }


    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void RActivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RActivoMousePressed
        if (RActivo.isSelected() && RActivo.isEnabled()) {
            RActivo.setText("Inactivo");
        } else {
            RActivo.setText("Activo");
        }
    }//GEN-LAST:event_RActivoMousePressed

    private void TxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtPrecioKeyTyped

    private void TxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TxtCodigoKeyTyped

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c != KeyEvent.VK_SPACE) && (Character.isLetter(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyReleased
        String texto = TxtPrecio.getText();
        if (!texto.equals("")) {
            try {
                texto = texto.replace(".", "");
                int precio = Integer.parseInt(texto);
                TxtPrecio.setText(String.valueOf(formato.format(precio)));
            } catch (Exception e) {
                System.out.println("Error " + e);
            }
        }
    }//GEN-LAST:event_TxtPrecioKeyReleased

    private void TxtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyReleased
        String texto = TxtCodigo.getText();
        if (!texto.equals("")) {
            int cant = texto.length();
            if (cant < 6) {
                texto1 = texto;
                TxtCodigo.setText(texto);
                if (cant == 5) {
                    TxtCodigo.setBackground(Color.decode("#BCEE68"));
                } else {
                    TxtCodigo.setBackground(Color.decode("#F9A28F"));
                }
            } else {
                TxtCodigo.setText(texto1);
                TxtCodigo.setBackground(Color.decode("#BCEE68"));
            }
        } else {
            TxtCodigo.setBackground(Color.decode("#F9A28F"));
        }
    }//GEN-LAST:event_TxtCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BtnAgregar;
    public static javax.swing.JRadioButton RActivo;
    private javax.swing.JSpinner SpinCantidad;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
