/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author 201611277427
 */
public class Splash extends javax.swing.JPanel {

    private ImageIcon fondo;
    private BorderLayout esquema;
    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
        initComponents();
        lblTexto.setForeground(new Color(102, 102, 102));
        fondo = new ImageIcon(getClass().getResource("/Img_Ventanas/Splash.jpg"));
        this.setSize(fondo.getIconWidth(), fondo.getIconHeight());
        this.setOpaque(false);
    }

    public void paintComponent(Graphics f) {
        super.paintComponent(f);
        f.drawImage(fondo.getImage(), 0, 0, fondo.getIconWidth(), fondo.getIconHeight(), this);
        this.setOpaque(true);
    }

    public void barra() throws InterruptedException {
        for (int cont = 0; cont < 109; cont++) {
            Thread.sleep(75);
            pgbBarra.setForeground(Color.DARK_GRAY);
            pgbBarra.setValue(cont);
            if (cont == 15) {
                lblTexto.setText("Inicializando Archivos");
            }
            if (cont == 20) {
                lblTexto.setText("Inicializando Archivos.");
            }
            if (cont == 30) {
                lblTexto.setText("Inicializando Archivos..");
            }
            if (cont == 40) {
                lblTexto.setText("Inicializando Archivos...");
            }
            if (cont == 45) {
                lblTexto.setText("Inicializando Plugins");
            }
            if (cont == 55) {
                lblTexto.setText("Inicializando Plugins.");
            }
            if (cont == 65) {
                lblTexto.setText("Inicializando Plugins..");
            }
            if (cont == 70) {
                lblTexto.setText("Inicializando Plugins...");
            }
            if (cont == 75) {
                lblTexto.setText("Inicializando Librerias");
            }
            if (cont == 80) {
                lblTexto.setText("Inicializando Librerias.");
            }
            if (cont == 85) {
                lblTexto.setText("Inicializando Librerias..");
            }
            if (cont == 90) {
                lblTexto.setText("Inicializando Librerias...");
            }
            if (cont == 93) {
                lblTexto.setText("Preparando Para iniciar");
            }
            if (cont == 96) {
                lblTexto.setText("Iniciando");
            }
            if (cont == 100) {
                lblTexto.setText("Iniciando.");
            }
            if (cont == 105) {
                lblTexto.setText("Iniciando..");
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgbBarra = new javax.swing.JProgressBar();
        lblTexto = new javax.swing.JLabel();

        lblTexto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Inicializando");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(pgbBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblTexto)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTexto;
    private javax.swing.JProgressBar pgbBarra;
    // End of variables declaration//GEN-END:variables
}
