/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Empresa;
import Model.Exportar;
import Model.Sistema;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 201611277427
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("VENTANA FACTURA");
        setIconImage(new ImageIcon(getClass().getResource("/Img_Ventanas/LogoFerre.png")).getImage());
        Cerrar();
        Nombres.setVisible(false);
        Empresa();
    }

    private void Cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    Confirmar();
                }
            });
            this.setVisible(true);
        } catch (Exception e) {
        }
    }

    private void Empresa() {
        Empresa empresa = new Empresa();
        if (!empresa.RegistroEmpresa()) {
            JOptionPane.showMessageDialog(rootPane, "Datos de la empresa no registrada");
            new DatosEmpresa().setVisible(true);
        }
    }

    public void Confirmar() {
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el Programa?", "Confirmacion", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            Sistema sistema = new Sistema();
            sistema.InsertarHistorial("Ha Cerrado Sesion");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lusuario = new javax.swing.JLabel();
        Nombres = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivos = new javax.swing.JMenu();
        ItemFacturar = new javax.swing.JMenuItem();
        ItemVerRegistros = new javax.swing.JMenuItem();
        ItemExportar = new javax.swing.JMenu();
        SubItemMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ItemCerrar = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();
        MenuProducto = new javax.swing.JMenu();
        ItemListaProducto = new javax.swing.JMenuItem();
        ItemInventario = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        ItemCliente = new javax.swing.JMenuItem();
        MenuConfig = new javax.swing.JMenu();
        ItemSistema = new javax.swing.JMenuItem();
        ItemHistorial = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventanas/Fondo main.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(730, 370));
        jLabel2.setPreferredSize(new java.awt.Dimension(729, 370));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Usuario : ");

        Lusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lusuario.setForeground(new java.awt.Color(0, 51, 51));
        Lusuario.setText("Usuario Ingresado");

        Nombres.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Nombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lusuario)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Lusuario)
                    .addComponent(Nombres))
                .addContainerGap())
        );

        MenuArchivos.setText("Archivos");

        ItemFacturar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK));
        ItemFacturar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/Compra.png"))); // NOI18N
        ItemFacturar.setText("Registrar Compra");
        ItemFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFacturarActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemFacturar);

        ItemVerRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemVerRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/archivo.png"))); // NOI18N
        ItemVerRegistros.setText("Facturas");
        ItemVerRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemVerRegistrosActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemVerRegistros);

        ItemExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/Exportar.png"))); // NOI18N
        ItemExportar.setText("Exportar");

        SubItemMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/Factura.png"))); // NOI18N
        SubItemMenu.setText("Facturas");
        SubItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubItemMenuActionPerformed(evt);
            }
        });
        ItemExportar.add(SubItemMenu);

        MenuArchivos.add(ItemExportar);
        MenuArchivos.add(jSeparator1);
        MenuArchivos.add(jSeparator2);

        ItemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/salida.png"))); // NOI18N
        ItemCerrar.setText("Cerrar Sesion");
        ItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCerrarActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemCerrar);

        ItemSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/boton-de-apagado.png"))); // NOI18N
        ItemSalir.setText("Salir");
        ItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSalirActionPerformed(evt);
            }
        });
        MenuArchivos.add(ItemSalir);

        jMenuBar1.add(MenuArchivos);

        MenuProducto.setText("Productos");

        ItemListaProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemListaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/lista.png"))); // NOI18N
        ItemListaProducto.setText("Lista Productos");
        ItemListaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListaProductoActionPerformed(evt);
            }
        });
        MenuProducto.add(ItemListaProducto);

        ItemInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/Productos.png"))); // NOI18N
        ItemInventario.setText("Inventario");
        ItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInventarioActionPerformed(evt);
            }
        });
        MenuProducto.add(ItemInventario);

        jMenuBar1.add(MenuProducto);

        MenuClientes.setText("Clientes");

        ItemCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/usuarios.png"))); // NOI18N
        ItemCliente.setText("Lista Cliente");
        ItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(ItemCliente);

        jMenuBar1.add(MenuClientes);

        MenuConfig.setText("Sistema");

        ItemSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ItemSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/ajustes.png"))); // NOI18N
        ItemSistema.setText("Configuracion");
        ItemSistema.setToolTipText("");
        ItemSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSistemaActionPerformed(evt);
            }
        });
        MenuConfig.add(ItemSistema);

        ItemHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/la-historia-clinica.png"))); // NOI18N
        ItemHistorial.setText("Historial");
        ItemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemHistorialActionPerformed(evt);
            }
        });
        MenuConfig.add(ItemHistorial);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Botones/banca.png"))); // NOI18N
        jMenuItem3.setText("Ventas de Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuConfig.add(jMenuItem3);

        jMenuBar1.add(MenuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemListaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListaProductoActionPerformed
        ListaProducto ver = new ListaProducto();
        ver.setVisible(true);
    }//GEN-LAST:event_ItemListaProductoActionPerformed

    private void ItemSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSistemaActionPerformed
        Configuracion ver = new Configuracion();
        ver.setVisible(true);
    }//GEN-LAST:event_ItemSistemaActionPerformed

    private void ItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClienteActionPerformed
        ListaCliente ver = new ListaCliente();
        ver.setVisible(true);
    }//GEN-LAST:event_ItemClienteActionPerformed

    private void ItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInventarioActionPerformed
        ListaInventario ver = new ListaInventario();
        ver.setVisible(true);
    }//GEN-LAST:event_ItemInventarioActionPerformed

    private void ItemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemHistorialActionPerformed
        new Historial().setVisible(true);
    }//GEN-LAST:event_ItemHistorialActionPerformed

    private void ItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSalirActionPerformed
        Confirmar();
    }//GEN-LAST:event_ItemSalirActionPerformed

    private void ItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCerrarActionPerformed
        this.dispose();
        Sistema sistema = new Sistema();
        sistema.InsertarHistorial("Ha Cerrado Sesion");
        new Login().setVisible(true);
    }//GEN-LAST:event_ItemCerrarActionPerformed

    private void SubItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubItemMenuActionPerformed
        if (ListaFactura.TablaFacturas.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay Datos en la Tabla de Factura");
        } else {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar Archivo");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<>();
                List<String> nom = new ArrayList<>();
                tb.add(ListaFactura.TablaFacturas);
                nom.add("Facturas");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exportar e = new Exportar(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Facturas Exportadas");
                        Sistema sistema = new Sistema();
                        sistema.InsertarHistorial("Ha Exportado Las Facturas");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Hubo un Error :" + e);
                }
            }
        }
    }//GEN-LAST:event_SubItemMenuActionPerformed

    private void ItemVerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemVerRegistrosActionPerformed
        new ListaFactura().setVisible(true);
    }//GEN-LAST:event_ItemVerRegistrosActionPerformed

    private void ItemFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFacturarActionPerformed
        new Facturar().setVisible(true);
    }//GEN-LAST:event_ItemFacturarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new VentasUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCerrar;
    private javax.swing.JMenuItem ItemCliente;
    public static javax.swing.JMenu ItemExportar;
    private javax.swing.JMenuItem ItemFacturar;
    private javax.swing.JMenuItem ItemHistorial;
    public javax.swing.JMenuItem ItemInventario;
    private javax.swing.JMenuItem ItemListaProducto;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSistema;
    public static javax.swing.JMenuItem ItemVerRegistros;
    public static javax.swing.JLabel Lusuario;
    private javax.swing.JMenu MenuArchivos;
    private javax.swing.JMenu MenuClientes;
    public javax.swing.JMenu MenuConfig;
    private javax.swing.JMenu MenuProducto;
    public static javax.swing.JLabel Nombres;
    private javax.swing.JMenuItem SubItemMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
